server:
  port: 8082

  error.include-message: always
#
#spring:
#  application:
#    name: devices-service

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
#  instance:
#    preferIpAddress: true

#springdoc:
#  version: '@springdoc.version@'

kafka:
  settings:
    bootstrapServers: "localhost:29092"
    acks: "1"
    batchSize: 16384
    linger: 1
    retries: 1
    bufferMemory: 33554432
    replicationFactor: 1

  topic:
    name: reeco_config_event
    core:
      name: core_backend
      partitions: 2
      replications: 1
      properties: "retention.ms:432000000;segment.bytes:26214400;retention.bytes:1048576000"