version: '3.9'

services:
  zookeeper:
    image: 'confluentinc/cp-zookeeper:6.1.0'
    cpus: 1
    mem_limit: 128m
    container_name: 'zookeeper'
    hostname: 'zookeeper'
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 2181 || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 20
    ports:
      - '2181:2181'
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_SERVER_ID=1

  broker:
    image: 'confluentinc/cp-kafka:6.1.0'
    cpus: 1
    mem_limit: 256m
    container_name: 'broker'
    hostname: 'broker'
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 9092 || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 20
    ports:
      - '29092:29092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://broker:19092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop
    hostname: 'kafka-ui'
    container_name: 'kafka-ui'
    restart: "no"
    ports:
      - "19000:9000"
    mem_limit: 128m
    cpus: 1
    environment:
      KAFKA_BROKERCONNECT: "broker:19092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - broker

  cassandra:
    image: scylladb/scylla
    mem_limit: 512m
    cpus: 1
    hostname: 'cassandra'
    container_name: 'cassandra'
    ports:
      - "9160:9160"
      - "9042:9042"
